services:
  postgres:
    image: postgres:15
    container_name: ocp_dataflow_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  etl:
    build: .
    container_name: ocp_dataflow_etl
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      LOG_DIR: /app/logs
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./src/etl/extract/etl_state.json:/app/src/etl/extract/etl_state.json
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

volumes:
  pgdata: